### ISSUE TITLE
Cannot Authorise

### ISSUE THREAD

**Issue by chinedu40** [MrAsterisco/homebridge-hisense-tv#1]
**Describe The Bug:**

Unable to authorise device
**To Reproduce:**

python3.8 hisensetv.py --authorize 192.168.86.15 --ifname eth1

**Expected behavior:**

For device to authorise

**Logs:**
Traceback (most recent call last):
  File "hisensetv.py", line 6, in <module>
    __main__.main()
  File "/volume1/docker/homebridge/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__main__.py", line 115, in main
    with tv:
  File "/volume1/docker/homebridge/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 137, in __enter__
    self._mqtt_client.connect(self.hostname, self.port)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1108)
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:  Docker

**Comment by MrAsterisco** [comment]
Hello @chinedu40 ! Thanks for reporting this. Could you please report your TV model? I believe this is related to some TV models using a self-signed SSL certificate. Could you also try to run this command?

```
python3.8 hisensetv.py --authorize 192.168.86.15 --ifname eth1 --no-ssl
```

Unfortunately, at the moment, there's no way to enable that parameter on the plugin configuration, but it shouldn't be a crazy change.

**Comment by chinedu40** [comment]
My TV model is 100L5 (the projector lazertv) 
I tried adding --no-ssl at the end and got the following

Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/bin/hisensetv", line 8, in <module>
    sys.exit(main())
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/hisensetv/__main__.py", line 108, in main
    with tv:
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/hisensetv/__init__.py", line 125, in __enter__
    raise HisenseTvTimeoutError(f"failed to connect in {self.timeout:.3f}s")
hisensetv.HisenseTvTimeoutError: failed to connect in 10.000s

Looking at forums i was able to use MQTT explorer and access my TV by following these instructions listed here https://github.com/d3nd3/Hisense-mqtt-keyfiles but i do not know if such a thing could be implemented into this application.

**Comment by MrAsterisco** [comment]
Ah, I see. In that case, you might have better luck posting this issue in the original [hisensetv tool](https://github.com/newAM/hisensetv) repo. If they manage to implement it, then there's a high chance we can also implement the same thing through Homebridge.

Closing as this is more of an issue in the underlying tool rather than the plugin itself.
