### ISSUE TITLE
Issues to pair TV on pi

### ISSUE THREAD

**Issue by catraska** [MrAsterisco/homebridge-hisense-tv#2]
**Describe The Bug:**

Issue when I try to pair TV with Homebridge
**To Reproduce:**

python3.7 hisensetv.py 10.0.1.43 --authorize --ifname eth0
**Expected behavior:**

It should connect to the TV and provide a code to pair home kit
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
root@homebridge:/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.7 hisensetv.py 10.0.1.43 --authorize --ifname eth0Traceback (most recent call last):
  File "hisensetv.py", line 3, in <module>
    from hisensetv import __main__
  File "/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 12, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'
**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
        {
            "ifname": "eth0",
            "devices": [
                {
                    "id": "HiSenseTV",
                    "name": "TV",
                    "ipaddress": "10.0.1.43",
                    "macaddress": "64:ae:f1:3c:40:d0 "
                }
            ],
            "platform": "HiSenseTV"
        }
    ]
}

**Screenshots:**

**Environment:**

* **Plugin Version**:
1.0.0
* **Homebridge Version**: 
Initializing HAP-NodeJS v0.9.4...
1.3.4
* **Node.js Version**: 
v12.19.0
* **NPM Version**: 
6.14.8
* **Operating System**: 
Raspbian

**Comment by chinedu40** [comment]
You need to install paho mqtt on your system

**Comment by MrAsterisco** [comment]
Thanks for reporting this! However, it seems to be related to #1 and #3 .

BTW, I would also make sure to remove the trailing space in the MAC Address, I'm not sure if I'm trimming the input before using it.

```
"macaddress": "64:ae:f1:3c:40:d0"
```

**Comment by MrAsterisco** [comment]
Should be fixed as part of #11 .
