### ISSUE TITLE
Error in hisensetv.py

### ISSUE THREAD

**Issue by MarNue75** [MrAsterisco/homebridge-hisense-tv#23]
**Describe Your Problem:**

Not able to run Phyton Script to autherize TV 
on Raspbian with Python 3.8.9

**Logs:**

 python  hisensetv.py 192.168.2.21 --authorize --ifname eth0
Traceback (most recent call last):
  File "hisensetv.py", line 3, in <module>
    from hisensetv import __main__
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 47
    def _check_connected(func: Callable):
                             ^
SyntaxError: invalid syntax

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
"ifname": "eth0",
    "devices": [
        {
            "id": "HiSenseTV",
            "name": "HiSense",
            "ipaddress": "192.168.2.21",
            "macaddress": "7C:B3:7B:76:5D:B6",
            "sslmode": "custom",
            "sslcertificate": "/tmp/ssl.cer",
            "sslprivatekey": "/tmp/priv.pkcs8"
        }
    ],
    "platform": "HiSenseTV"


**Environment:**

* **Plugin Version**:
* **Homebridge Version**: <!-- homebridge -V -->
   
1.3.5

* **Node.js Version**: <!-- node -v --> 

 v16.13.0

* **NPM Version**: <!-- npm -v -->

  8.1.0

* **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->

 Raspbian

**Comment by MrAsterisco** [comment]
@MarNue75 Thanks for opening this issue, unfortunately I don't have a Raspberry to debug the problem. It looks like something changed in your Python version and something we're using it's not supported.

Would you be comfortable debugging this on your own and opening a PR?

**Comment by MarNue75** [comment]
Hi,

sure ... but I will need a little advice what to do ...

**Comment by MrAsterisco** [comment]
Sure, I'm happy to help!

So this plugin is built over a Python script, that lives in [in this other repo](https://github.com/MrAsterisco/hisensetv). This script is responsible of talking with the TV, using the communication protocol that the RemoteNOW app uses.

Your Python version is complaining about a syntax error in line 47 of the init.py file, so [here](https://github.com/MrAsterisco/hisensetv/blob/5d5863aa9cbcae1c769bad8888d4813d48e9a36d/hisensetv/__init__.py#L47).

My first hunch here would be that Python isn't happy about the `_` at the beginning of the function name, so I'd probably try to just open the file:

```bash
nano /usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/init.py
```

and then scroll down to line 47 and remove the `_`, resulting in something like this:

```python
def check_connected(func: Callable):
```

You'll then have to update all the places where this wrapper is used and you can do that by searching for `_check_connected` in the file and removing the `_` from all of them. You should have around 50 calls of that wrapper.

If you have SSH access to your server, I'd then suggest to use a more modern editor to do this change, like Visual Studio Code.

Once you've done the change, you can just run the Python script again.

_If this fixes it, you'll have to open a PR on the Python script repo, so that we can release a new version and then update the plugin as well. But we'll cross that bridge once we come to it._

**Comment by MrAsterisco** [comment]
Closing as there was no activity for quite some time. Feel free to reopen when you're tackling this.
