### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by mensa84** [MrAsterisco/homebridge-hisense-tv#28]
Hello,

I always get that SSL errors. Can you please help me how to fixthis?

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.9 hisensetv.py 192.168.1.40 --authorize --ifname ens3
[2022-01-16 20:09:04,355] [INFO    ] Unverified SSL context created.
Traceback (most recent call last):
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv.py", line 6, in <module>
    __main__.main()
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__main__.py", line 128, in main
    with tv:
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 137, in __enter__
    self._mqtt_client.connect(self.hostname, self.port)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)
`

Also --no-ssl also does not help:

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.9 hisensetv.py 192.168.1.40 --authorize --ifname ens3 --no-ssl
[2022-01-16 20:12:54,347] [INFO    ] No SSL context specified.
Traceback (most recent call last):
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv.py", line 6, in <module>
    __main__.main()
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__main__.py", line 128, in main
    with tv:
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 145, in __enter__
    raise HisenseTvTimeoutError(f"failed to connect in {self.timeout:.3f}s")
hisensetv.HisenseTvTimeoutError: failed to connect in 10.000s
`

**Comment by mensa84** [comment]
It was solved using that SSL files: https://github.com/MrAsterisco/hisensetv/tree/master/cert
