### ISSUE TITLE
Can someone help me pair the tv with Homebridge

### ISSUE THREAD

**Issue by xXMrEzXx** [MrAsterisco/homebridge-hisense-tv#48]
**Describe Your Problem:**
After moving the Node_Modules folder into hisense-tv-remotenow i cannot run the script.
I've tried this in windows first, now im running a Hyper-V instance with Ubuntu and Docker

Environment:

* **plugin version 2.0.0**:
* **Homebridge Version**: <1.6.1>
* **Node.js Version**: <18.13.0>
* **NPM Version**: <8.19.3>
* **Operating System**:  Ubuntu on Hyper-V VM with docker

**Comment by MrAsterisco** [comment]
Hey @xXMrEzXx !

In order to help you, we're going to need more information 😊 What error exactly are you seeing? What commands are you giving?

**Comment by xXMrEzXx** [comment]
I get a syntax error

**Comment by xXMrEzXx** [comment]
could you maybe explain me how i have to pair the TV with homebridge when using the hyper-V version?

**Comment by MrAsterisco** [comment]
Hey @xXMrEzXx !

First thing I'd verify is that you're running the correct version of Python. Please, refer to [the Requirements section](https://github.com/MrAsterisco/homebridge-hisense-tv#requirements) for further details.

The procedure to pair your TV with the plugin is also described in the Readme. 😊 

Your specific configuration shouldn't affect how this plugin works, but you should be aware that it's impossible for me to test every single possible combination of hardware, software, and virtual machine provider, so you'll have to adapt the instructions for your specific case. As you were able to install the machine in Hyper-V, I assume you know more than me on that system. 😉

**Comment by xXMrEzXx** [comment]
now i get this:

python3.8 hisensetv.py 192.168.1.140 --authorize --ifname eth0
python3.8: can't open file 'hisensetv.py': [Errno 2] No such file or directory

**Comment by MrAsterisco** [comment]
Well, the error is telling you that there is no file called `hysensetv.py` in the folder you're executing this command in. Verify that you are in the right folder.

**Comment by xXMrEzXx** [comment]
now im getting following error:

Traceback (most recent call last):
  File "hisensetv.py", line 3, in <module>
    from hisensetv import __main__
  File "/var/lib/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 17, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

**Comment by MrAsterisco** [comment]
Hey @xXMrEzXx ! It looks like you haven't followed the instructions to install the required dependencies on your machine: please, review [the Readme](https://github.com/MrAsterisco/homebridge-hisense-tv#linux-including-hoobs) and make sure you follow all the steps described there.

I will close this issue for now, as this seems to be a configuration issue on your end. Feel free to reopen it, if you encounter an actual issue with the plugin. Thank you!
